### PR TITLE
pull: Update to the SPDX License List 3.0

### PR DESCRIPTION
**Pull request by wking**
As [released 2017-12-28][1].  The main change here is that the same license can now have multiple license-list entries, with each entry covering a common grant.  I think conflating licenses with grants is unfortunate, and would have preferred continuing to handle version grants with [the `+` license expression operator][2] and possibly a new [`-ONLY` operator][3].  But that ship seems to have sailed.

This commit converts the SPDX identifiers into lists, so we can list as many identifiers as we want for each FSF license ID.  It also adds property docs, so folks understand the significance of the identifier ordering.

I cheat a bit on the `fsf-list-practical` link, because the FSF hasn't put an anchor on that header.  Instead, I'm using the first entry underneath the header.

Also convert `uri` to the plural `uris`.  There are enough hacks here that we should make it easy for folks to go back and double-check our calls.

[1]: https://github.com/spdx/license-list-XML/releases/tag/v3.0
[2]: https://spdx.org/spdx-specification-21-web-version#h.jxpfx0ykyb60
[3]: https://lists.spdx.org/pipermail/spdx-legal/2017-August/002126.html

### CODE REVIEW

**Comment by wking** [comment]
Even before 3.0, SPDX used per-grant identifiers for `MPL-2.0` and `MPL-2.0-no-copyleft-exception` (spdx/license-list-XML#441).  But my reading of [the FSF's `MPL-2.0` position][1] gives me the     impression that the FSF's GPL-compatibility ruling hinges on §3.3, which is what the `MPL-2.0-no-copyleft-exception` is turning off.  So I've left mapping at FSF `MPL-2.0` → SPDX `MPL-2.0`, instead of growing it to `[MPL-2.0, MPL-2.0-no-copyleft-exception]`.

[1]: https://www.gnu.org/licenses/license-list.html#MPL-2.0

**Comment by goneall** [comment]
This actually does break the current set of SPDX tools due to the incompatibility in the type.  The tool is pull directly from https://wking.github.io/fsf-api/licenses-full.json

I'll update the tools to handle this, but the current release will break (e.g. the version used in the pull requests for license-list-XML testing/deployment).

We should version the output of this so that the tooling can check the version for incompatibilities.  I'll create a separate issue to track adding version.

**Comment by wking** [comment]
On Thu, Jan 04, 2018 at 07:58:42PM +0000, goneall wrote:
> The tool is pull directly from
> https://wking.github.io/fsf-api/licenses-full.json

Ah, sorry.  I thought the tools vendored this [1].  What's the purpose
of having [1] in the tools repo if the tools are pulling from the live
site?

> We should version the output of this so that the tooling can check
> the version for incompatibilities.  I'll create a separate issue to
> track adding version.

Versioning the output is a good idea though.

[1]: https://github.com/spdx/tools/blob/v2.1.8/resources/licenses-full.json

**Comment by goneall** [comment]
> Ah, sorry.  I thought the tools vendored this [1].  

No worries - I can see why you would come to that conclusion.

The tool tries to access the live version and if it can not access it (e.g. network failure), it falls back to the vendored version.

I can extend the checks for a version and use the vendored version if the version number is incompatible.  I thought about falling back on other errors, but that would be more difficult since the error can occur much later than when the JSON is deserialized.

**Comment by goneall** [comment]
Now that I think about it, I should add a property to force it to use the vendored version as well (I take this approach for the license list itself).

**Pull request merged**
